jobs:
- job: Build_and_Test
  displayName: Build and Test
  condition: succeeded()
  pool:
    name: Hosted Ubuntu 1604
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 3

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install --upgrade pip
    displayName: 'Upgrade pip'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      flake8 --max-line-length=120 *.py tests/ scripts/
    displayName: 'Run lint (flake8) tests'

  - script: |
      pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov --cov-report=xml --cov-report=html
    displayName: pytest

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/test-results.xml'
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
    