name: straatvinken-dl
# a conda specification for the deep learning bit of image segmentation
dependencies:
  - python=3.8.12
  - conda
  - pip
  - pip:
    - numpy==1.22.1
    - h5py==2.10.0
    - keras==2.4.3
    - opencv-python==4.5.5.62
    - tqdm==4.62.3
    - joblib==1.1.0
    - tensorflow==2.2.0
    - keras-segmentation==0.3.0
    - pandas==1.3.5
    - ipykernel==6.7.0
    - torch==1.10.0
    - torchvision==0.11.1
# register kernel after installation (so that it becomes available in jupyter notebook)
# python -m ipykernel install --user --name straatvinken-dl --display-name "Python 3.8.2 (straatvinken-dl)"







