name: straatvinken
dependencies:
  - python=3.8.12
  - pip
  - numpy=1.20.3
  - python-dateutil=2.8.2
  - pandas==1.3.5
  - pytest=5.3.1
  - pytest-cov=2.8.1
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - gdal=3.4.1
  - lightgbm=3.3.2
  - pip:
    - azureml-sdk
    - joblib==0.14.1
    - matplotlib==3.1.2
    - scikit-learn==1.0.2
    - python-dotenv==0.19.2
    - ipython-sql
    - geopandas==0.10.2
    - ipywidgets==7.6.5
    - contextily==1.2.0
    - georasters # has a crazy amount of dependencies
    - openpyxl # for using pandas.read_excel()
    - google_streetview
    - seaborn
    - simpledbf==0.2.6
    - streamlit==1.4.0
    - brewer2mpl==1.4.1
    - xgboost==1.5.2
    - catboost==1.0.4
    - pytorch-tabnet==3.1.1
    - branca==0.4.2
    - folium==0.12.1.post1
    - tables==3.7.0
    - streamlit-folium==0.6.4
    - shap==0.40.0
    
