iteration: '2022_3'
date_created: '2022-03-09'
dataset_path: 'data/processed/20220309_straatvinken_abt_complete_df.pkl'
columns:
  Y_s:
  - bike
  - bus
  - car
  - truck
  - van
  - walk
  explain_cols:
  - ID
  - lat
  - long
  one_hot_cols:
  - morf
  - wegcat
  num_pred_remain_cols:
  - kc_kern_prop
  - kern_prop
  - bmc_prop
  - lu_park_prop
  - lu_grass_prop
  - lu_industrial_prop
  - lu_forest_prop
  - lu_meadow_prop
  - lu_residential_prop
  - lu_farmland_prop
  - lu_commercial_prop
  num_pred_minmax_cols:
  - bedi
  - pode
  - nhh
  - ncars
  - ncars_hh
  - ms_pop
  - acc
  - acc_death
  - acc_death30
  - acc_mort
  - acc_ser
  - acc_sly
  - nrijstr
  - wb
  - morf_101_50
  - morf_102_50
  - morf_103_50
  - morf_104_50
  - morf_105_50
  - morf_106_50
  - morf_107_50
  - morf_108_50
  - morf_109_50
  - morf_110_50
  - morf_111_50
  - morf_112_50
  - morf_113_50
  - morf_114_50
  - morf_116_50
  - morf_120_50
  - morf_125_50
  - morf_130_50
  - wegcat_H_50
  - wegcat_L1_50
  - wegcat_L2_50
  - wegcat_L3_50
  - wegcat_L_50
  - wegcat_PI_50
  - wegcat_PII-1_50
  - wegcat_PII-2_50
  - wegcat_PII-4_50
  - wegcat_PII_50
  - wegcat_S1_50
  - wegcat_S2_50
  - wegcat_S3_50
  - wegcat_S4_50
  - wegcat_S_50
  - wegcat_Ltot_50
  - wegcat_Ptot_50
  - wegcat_Stot_50
  - morf_101_250
  - morf_102_250
  - morf_103_250
  - morf_104_250
  - morf_105_250
  - morf_106_250
  - morf_107_250
  - morf_108_250
  - morf_109_250
  - morf_110_250
  - morf_111_250
  - morf_112_250
  - morf_113_250
  - morf_114_250
  - morf_116_250
  - morf_120_250
  - morf_125_250
  - morf_130_250
  - wegcat_H_250
  - wegcat_L1_250
  - wegcat_L2_250
  - wegcat_L3_250
  - wegcat_L_250
  - wegcat_PI_250
  - wegcat_PII-1_250
  - wegcat_PII-2_250
  - wegcat_PII-4_250
  - wegcat_PII_250
  - wegcat_S1_250
  - wegcat_S2_250
  - wegcat_S3_250
  - wegcat_S4_250
  - wegcat_S_250
  - wegcat_Ltot_250
  - wegcat_Ptot_250
  - wegcat_Stot_250
  - morf_101_1000
  - morf_102_1000
  - morf_103_1000
  - morf_104_1000
  - morf_105_1000
  - morf_106_1000
  - morf_107_1000
  - morf_108_1000
  - morf_109_1000
  - morf_110_1000
  - morf_111_1000
  - morf_112_1000
  - morf_113_1000
  - morf_114_1000
  - morf_116_1000
  - morf_120_1000
  - morf_125_1000
  - morf_130_1000
  - wegcat_H_1000
  - wegcat_L1_1000
  - wegcat_L2_1000
  - wegcat_L3_1000
  - wegcat_L_1000
  - wegcat_PI_1000
  - wegcat_PII-1_1000
  - wegcat_PII-2_1000
  - wegcat_PII-4_1000
  - wegcat_PII_1000
  - wegcat_S1_1000
  - wegcat_S2_1000
  - wegcat_S3_1000
  - wegcat_S4_1000
  - wegcat_S_1000
  - wegcat_Ltot_1000
  - wegcat_Ptot_1000
  - wegcat_Stot_1000
  - school_D_dist3 
  - school_B_dist3 
  - school_S_dist3 
  - school_V_dist3 
  - school_H_dist3
  - kc_lint_len
  - lint_len
  - trfeat_motorway_junction_dist3
  - trfeat_speed_camera_dist3
  - trfeat_crossing_dist3
  - trfeat_traffic_signals_dist3
  - trfeat_mini_roundabout_dist3
  - trfeat_turning_circle_dist3
  - trfeat_lock_gate_dist3
  - trfeat_fuel_dist3
  - trfeat_parking_underground_dist3
  - trfeat_stop_dist3
  - trfeat_parking_dist3
  - trfeat_slipway_dist3
  - trfeat_street_lamp_dist3
  - trfeat_marina_dist3
  - trfeat_weir_dist3
  - trfeat_parking_bicycle_dist3
  - trfeat_dam_dist3
  - trfeat_pier_dist3
  - trfeat_waterfall_dist3
  - trfeat_parking_multistorey_dist3
  - trfeatp_parking_dist3
  - trfeatp_marina_dist3
  - trfeatp_parking_bicycle_dist3
  - trfeatp_parking_multistorey_dist3
  - trfeatp_parking_underground_dist3
  - trfeatp_fuel_dist3
  - trfeatp_pier_dist3
  - trfeatp_dam_dist3
  - trfeatp_service_dist3
  - trfeatp_slipway_dist3
  - trfeatp_weir_dist3
  - trfeatp_lock_gate_dist3
  - trfeatp_waterfall_dist3
  num_pred_segm_cols:
  - segm_wall
  - segm_building
  - segm_sky
  - segm_tree
  - segm_road
  - segm_grass
  - segm_sidewalk
  - segm_car
  - segm_fence
  - segm_signboard
  - segm_pole
  - segm_person
  - segm_plant
  - segm_stairs
  - segm_bridge
  - segm_streetlight
  - segm_earth
  - segm_water
  - segm_rock
  - segm_box
  - segm_sand
  - segm_path
  - segm_bench
  - segm_house
  - segm_van
  - segm_minibike
  - segm_ashcan
  - segm_pot
  - segm_mountain
  - segm_door
  - segm_trade
  - segm_field
  - segm_floor
  - segm_dirt
  - segm_flower
  - segm_truck
  - segm_railing
  - segm_boat
  - segm_conveyer
  - segm_windowpane
  - segm_ceiling
  - segm_stairway
  - segm_bus
  - segm_bicycle
  - segm_cabinet
  - segm_table
  - segm_awning
  - segm_bannister
  - segm_escalator
  - segm_bed
